### ISSUE TITLE
[BUG] yarn build - digital envelope routines::unsupported 

### ISSUE THREAD

**Issue by surfer190** [bitcart/bitcart#297]
**Describe the bug**

Running `yarn build` raises an error:

```
ℹ Production build                                                                                                                                                                       20:37:26
ℹ Bundling for server and client side                                                                                                                                                    20:37:26
ℹ Target: server                                                                                                                                                                         20:37:26
✔ Builder initialized                                                                                                                                                                    20:37:26
✔ Nuxt files generated                                                                                                                                                                   20:37:26

● Client █████████████████████████ building (10%) 1/2 modules 1 active
 babel-loader › .nuxt/client.js

◯ Server
  


 ERROR  Error: error:0308010C:digital envelope routines::unsupported                                                                                                                     20:37:29
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/var/www/bitcart-store/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/bitcart-store/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/bitcart-store/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/bitcart-store/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/bitcart-store/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/var/www/bitcart-store/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/var/www/bitcart-store/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /var/www/bitcart-store/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9


 ERROR  error:0308010C:digital envelope routines::unsupported                                                                                                                            20:37:31

  at new Hash (node:internal/crypto/hash:67:19)
  at Object.createHash (node:crypto:135:10)
  at module.exports (node_modules/webpack/lib/util/createHash.js:135:53)
  at NormalModule._initBuildHash (node_modules/webpack/lib/NormalModule.js:417:16)
  at handleParseError (node_modules/webpack/lib/NormalModule.js:471:10)
  at node_modules/webpack/lib/NormalModule.js:503:5
  at node_modules/webpack/lib/NormalModule.js:358:12
  at node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
  at iterateNormalLoaders (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
  at iterateNormalLoaders (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
  at node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:236:3
  at context.callback (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
  at node_modules/babel-loader/lib/index.js:59:71
```

**To Reproduce**

1. Follow the [manual installation steps](https://docs.bitcartcc.com/deployment/manual)
2. Get to the [admin and store setup](https://docs.bitcartcc.com/deployment/manual#bitcartcc-admin-panel)
3. Run `yarn`
4. Run `yarn build`

**Expected behavior**

Expected to succeed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Debian GNU/Linux 9.13 (stretch)
- Store version: Version 0.6.8.1
- Admin version: Version 0.6.8.1
- Bitcart version: Version 0.6.8.1
- `yarn --version`: 3.2.2
- `npm -v`: 8.5.5
- `nodejs -v`: v17.9.0

**Comment by MrNaif2018** [comment]
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

We use nodejs 16, please install that version

**Comment by MrNaif2018** [comment]
By the way, this is now fixed. We now use the latest nodejs LTS 18, so we now have a workaround for this issue in place
