### ISSUE TITLE
[BUG] Tron node not running

### ISSUE THREAD

**Issue by k1meister** [bitcart/bitcart#440]
I get the error in bitcart admin panel:

TRX node not running

Connected to 0 nodes, current height: 0
Some functions may not work properly

- OS: Ubuntu 22.04.5 LTS

In logs:

2024-11-20 15:37:26,137 - [PID 1] - api.ext.update.refresh [line 89] - INFO - Checking for updates...
2024-11-20 15:37:26,194 - [PID 1] - api.ext.update.refresh [line 95] - INFO - No updates found
2024-11-20 17:08:59,291 - [PID 1] - api.settings.log_startup_info [line 339] - INFO - Bitcart version: 0.8.0.0 - https://bitcart.ai - https://github.com/bitcart/bitcart
2024-11-20 17:08:59,305 - [PID 1] - api.settings.log_startup_info [line 340] - INFO - Python version: 3.9.18 (main, Sep  7 2023, 13:38:29) 
[GCC 10.2.1 20210110]. On platform: Linux-5.15.0-122-generic-x86_64-with-glibc2.31
2024-11-20 17:08:59,306 - [PID 1] - api.settings.log_startup_info [line 341] - INFO - BITCART_CRYPTOS=btc,bch,eth,bnb,ltc,trx; IN_DOCKER=True; LOG_FILE=bitcart.log
2024-11-20 17:08:59,306 - [PID 1] - api.settings.log_startup_info [line 345] - INFO - Successfully loaded 6 cryptos
2024-11-20 17:08:59,306 - [PID 1] - api.settings.log_startup_info [line 346] - INFO - 17 notification providers available
2024-11-20 17:08:59,327 - [PID 1] - api.ext.update.refresh [line 89] - INFO - Checking for updates...
2024-11-20 17:08:59,381 - [PID 1] - api.ext.update.refresh [line 95] - INFO - No updates found

Any idea?

Thanks for any help.

**Comment by MrNaif2018** [comment]
docker logs compose-tron-1
would tell the issue

**Comment by k1meister** [comment]
Yeah I tried that actually I cannot see anything, tried to reboot server etc. but same after all, bitcart is installed for a few days and did nothing to it:

Output:
```shell
root@bitcart:~# docker logs compose-tron-1
======== Running on http://0.0.0.0:5009 ========
(Press CTRL+C to quit)
root@bitcart:~# 
```

**Comment by MrNaif2018** [comment]
export TRX_DEBUG=true
./setup.sh

**Comment by k1meister** [comment]
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 1
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 2
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 3
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 4
Failed after 5 retries: make_request ('wallet/getnodeinfo',) {}
Retrying make_request ('wallet/getnowblock', {'visible': True}) {}, attempt 1
Retrying make_request ('wallet/getnowblock', {'visible': True}) {}, attempt 2
Retrying make_request ('wallet/getnowblock', {'visible': True}) {}, attempt 3
Retrying make_request ('wallet/getnowblock', {'visible': True}) {}, attempt 4
Failed after 5 retries: make_request ('wallet/getnowblock', {'visible': True}) {}
Error processing pending blocks:
Traceback (most recent call last):
  File "/home/electrum/site/daemons/trx.py", line 63, in get_block_number
    return await self.web3.get_latest_block_number()
  File "/home/electrum/.local/lib/python3.9/site-packages/tronpy/async_tron.py", line 842, in get_latest_block_number
    info = await self.provider.make_request("wallet/getnodeinfo")
  File "/home/electrum/site/daemons/utils.py", line 196, in middleware
    result = await make_request(*args, **kwargs)
  File "/home/electrum/.local/lib/python3.9/site-packages/tronpy/providers/async_http.py", line 57, in make_request
    resp.raise_for_status()
  File "/home/electrum/.local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://rpc.ankr.com/http/tron/wallet/getnodeinfo'
For more information check: https://httpstatuses.com/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/electrum/site/daemons/genericprocessor.py", line 662, in process_pending
    current_height = await self.coin.get_block_number()
  File "/home/electrum/site/daemons/trx.py", line 65, in get_block_number
    block_data = await self.web3.get_latest_block()
  File "/home/electrum/.local/lib/python3.9/site-packages/tronpy/async_tron.py", line 831, in get_latest_block
    return await self.provider.make_request("wallet/getnowblock", {"visible": True})
  File "/home/electrum/site/daemons/utils.py", line 196, in middleware
    result = await make_request(*args, **kwargs)
  File "/home/electrum/.local/lib/python3.9/site-packages/tronpy/providers/async_http.py", line 57, in make_request
    resp.raise_for_status()
  File "/home/electrum/.local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://rpc.ankr.com/http/tron/wallet/getnowblock'
For more information check: https://httpstatuses.com/403

Retrying make_request ('wallet/getnodeinfo',) {}, attempt 1
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 2
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 3
Retrying make_request ('wallet/getnodeinfo',) {}, attempt 4
Failed after 5 retries: make_request ('wallet/getnodeinfo',) {}
Retrying make_request ('wallet/getnowblock', {'visible': True}) {}, attempt 1
Retrying make_request ('wallet/getnowblock', {'visible': True}) {}, attempt 2
Retrying make_request ('wallet/listnodes', {'visible': True}) {}, attempt 1

**Comment by MrNaif2018** [comment]
https://t.me/bitcart/54554

**Comment by k1meister** [comment]
Thanks mate

**Comment by smileBeda** [comment]
Same issue here, with TRX and Matic.
I cannot join Telegram (I do not want to use that application, it is a spam tool).

May I know what was the solution to this problem?
It happens on my fresh install, with configurator.

Thank you!

**Comment by MrNaif2018** [comment]
Please, don't spam issues. If I see correctly, you joined discord, which is bridged to our telegram, so you can ask telegram users from discord without ever installing telegram. We even have a matrix community which is also bridged between discord and telegram. In fact one of your first questions was already answered and you received them in discord, please ask in community
